export const KycTypes = [
  {
    label: 'Personal KYC',
    value: 'Personal',
  },
  // {
  //   label: 'Enterprise KYC',
  //   value: 'Company',
  // },
];

export const dateRange = [
  {label: 'Current Month', value: 'Current Month'},
  {label: 'Current Financial Year', value: 'Current Financial Year'},
  {label: 'Past Financial Year', value: 'Past Financial Year'},
];

export const accountTypes = [
  {
    label: 'Saving Account',
    value: 'Saving Account',
  },
  {
    label: 'Current Account',
    value: 'Current Account',
  },
  {
    label: 'Fixed Deposit Account',
    value: 'Fixed Deposit Account',
  },
];
export const countryList = [
  {
    id: 1,
    label: 'Afghanistan',
    value: 'Afghanistan',
  },
  {
    id: 2,
    label: 'Aland Islands',
    value: 'Aland Islands',
  },
  {
    id: 3,
    label: 'Albania',
    value: 'Albania',
  },
  {
    id: 4,
    label: 'Algeria',
    value: 'Algeria',
  },
  {
    id: 5,
    label: 'American Samoa',
    value: 'American Samoa',
  },
  {
    id: 6,
    label: 'Andorra',
    value: 'Andorra',
  },
  {
    id: 7,
    label: 'Angola',
    value: 'Angola',
  },
  {
    id: 8,
    label: 'Anguilla',
    value: 'Anguilla',
  },
  {
    id: 9,
    label: 'Antarctica',
    value: 'Antarctica',
  },
  {
    id: 10,
    label: 'Antigua And Barbuda',
    value: 'Antigua And Barbuda',
  },
  {
    id: 11,
    label: 'Argentina',
    value: 'Argentina',
  },
  {
    id: 12,
    label: 'Armenia',
    value: 'Armenia',
  },
  {
    id: 13,
    label: 'Aruba',
    value: 'Aruba',
  },
  {
    id: 14,
    label: 'Australia',
    value: 'Australia',
  },
  {
    id: 15,
    label: 'Austria',
    value: 'Austria',
  },
  {
    id: 16,
    label: 'Azerbaijan',
    value: 'Azerbaijan',
  },
  {
    id: 17,
    label: 'The Bahamas',
    value: 'The Bahamas',
  },
  {
    id: 18,
    label: 'Bahrain',
    value: 'Bahrain',
  },
  {
    id: 19,
    label: 'Bangladesh',
    value: 'Bangladesh',
  },
  {
    id: 20,
    label: 'Barbados',
    value: 'Barbados',
  },
  {
    id: 21,
    label: 'Belarus',
    value: 'Belarus',
  },
  {
    id: 22,
    label: 'Belgium',
    value: 'Belgium',
  },
  {
    id: 23,
    label: 'Belize',
    value: 'Belize',
  },
  {
    id: 24,
    label: 'Benin',
    value: 'Benin',
  },
  {
    id: 25,
    label: 'Bermuda',
    value: 'Bermuda',
  },
  {
    id: 26,
    label: 'Bhutan',
    value: 'Bhutan',
  },
  {
    id: 27,
    label: 'Bolivia',
    value: 'Bolivia',
  },
  {
    id: 28,
    label: 'Bosnia and Herzegovina',
    value: 'Bosnia and Herzegovina',
  },
  {
    id: 29,
    label: 'Botswana',
    value: 'Botswana',
  },
  {
    id: 30,
    label: 'Bouvet Island',
    value: 'Bouvet Island',
  },
  {
    id: 31,
    label: 'Brazil',
    value: 'Brazil',
  },
  {
    id: 32,
    label: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  {
    id: 33,
    label: 'Brunei',
    value: 'Brunei',
  },
  {
    id: 34,
    label: 'Bulgaria',
    value: 'Bulgaria',
  },
  {
    id: 35,
    label: 'Burkina Faso',
    value: 'Burkina Faso',
  },
  {
    id: 36,
    label: 'Burundi',
    value: 'Burundi',
  },
  {
    id: 37,
    label: 'Cambodia',
    value: 'Cambodia',
  },
  {
    id: 38,
    label: 'Cameroon',
    value: 'Cameroon',
  },
  {
    id: 39,
    label: 'Canada',
    value: 'Canada',
  },
  {
    id: 40,
    label: 'Cape Verde',
    value: 'Cape Verde',
  },
  {
    id: 41,
    label: 'Cayman Islands',
    value: 'Cayman Islands',
  },
  {
    id: 42,
    label: 'Central African Republic',
    value: 'Central African Republic',
  },
  {
    id: 43,
    label: 'Chad',
    value: 'Chad',
  },
  {
    id: 44,
    label: 'Chile',
    value: 'Chile',
  },
  {
    id: 45,
    label: 'China',
    value: 'China',
  },
  {
    id: 46,
    label: 'Christmas Island',
    value: 'Christmas Island',
  },
  {
    id: 47,
    label: 'Cocos (Keeling) Islands',
    value: 'Cocos (Keeling) Islands',
  },
  {
    id: 48,
    label: 'Colombia',
    value: 'Colombia',
  },
  {
    id: 49,
    label: 'Comoros',
    value: 'Comoros',
  },
  {
    id: 50,
    label: 'Congo',
    value: 'Congo',
  },
  {
    id: 51,
    label: 'Democratic Republic of the Congo',
    value: 'Democratic Republic of the Congo',
  },
  {
    id: 52,
    label: 'Cook Islands',
    value: 'Cook Islands',
  },
  {
    id: 53,
    label: 'Costa Rica',
    value: 'Costa Rica',
  },
  {
    id: 54,
    label: "Cote D'Ivoire (Ivory Coast)",
    value: "Cote D'Ivoire (Ivory Coast)",
  },
  {
    id: 55,
    label: 'Croatia',
    value: 'Croatia',
  },
  {
    id: 56,
    label: 'Cuba',
    value: 'Cuba',
  },
  {
    id: 57,
    label: 'Cyprus',
    value: 'Cyprus',
  },
  {
    id: 58,
    label: 'Czech Republic',
    value: 'Czech Republic',
  },
  {
    id: 59,
    label: 'Denmark',
    value: 'Denmark',
  },
  {
    id: 60,
    label: 'Djibouti',
    value: 'Djibouti',
  },
  {
    id: 61,
    label: 'Dominica',
    value: 'Dominica',
  },
  {
    id: 62,
    label: 'Dominican Republic',
    value: 'Dominican Republic',
  },
  {
    id: 63,
    label: 'East Timor',
    value: 'East Timor',
  },
  {
    id: 64,
    label: 'Ecuador',
    value: 'Ecuador',
  },
  {
    id: 65,
    label: 'Egypt',
    value: 'Egypt',
  },
  {
    id: 66,
    label: 'El Salvador',
    value: 'El Salvador',
  },
  {
    id: 67,
    label: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
  },
  {
    id: 68,
    label: 'Eritrea',
    value: 'Eritrea',
  },
  {
    id: 69,
    label: 'Estonia',
    value: 'Estonia',
  },
  {
    id: 70,
    label: 'Ethiopia',
    value: 'Ethiopia',
  },
  {
    id: 71,
    label: 'Falkland Islands',
    value: 'Falkland Islands',
  },
  {
    id: 72,
    label: 'Faroe Islands',
    value: 'Faroe Islands',
  },
  {
    id: 73,
    label: 'Fiji Islands',
    value: 'Fiji Islands',
  },
  {
    id: 74,
    label: 'Finland',
    value: 'Finland',
  },
  {
    id: 75,
    label: 'France',
    value: 'France',
  },
  {
    id: 76,
    label: 'French Guiana',
    value: 'French Guiana',
  },
  {
    id: 77,
    label: 'French Polynesia',
    value: 'French Polynesia',
  },
  {
    id: 78,
    label: 'French Southern Territories',
    value: 'French Southern Territories',
  },
  {
    id: 79,
    label: 'Gabon',
    value: 'Gabon',
  },
  {
    id: 80,
    label: 'Gambia The',
    value: 'Gambia The',
  },
  {
    id: 81,
    label: 'Georgia',
    value: 'Georgia',
  },
  {
    id: 82,
    label: 'Germany',
    value: 'Germany',
  },
  {
    id: 83,
    label: 'Ghana',
    value: 'Ghana',
  },
  {
    id: 84,
    label: 'Gibraltar',
    value: 'Gibraltar',
  },
  {
    id: 85,
    label: 'Greece',
    value: 'Greece',
  },
  {
    id: 86,
    label: 'Greenland',
    value: 'Greenland',
  },
  {
    id: 87,
    label: 'Grenada',
    value: 'Grenada',
  },
  {
    id: 88,
    label: 'Guadeloupe',
    value: 'Guadeloupe',
  },
  {
    id: 89,
    label: 'Guam',
    value: 'Guam',
  },
  {
    id: 90,
    label: 'Guatemala',
    value: 'Guatemala',
  },
  {
    id: 91,
    label: 'Guernsey and Alderney',
    value: 'Guernsey and Alderney',
  },
  {
    id: 92,
    label: 'Guinea',
    value: 'Guinea',
  },
  {
    id: 93,
    label: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
  },
  {
    id: 94,
    label: 'Guyana',
    value: 'Guyana',
  },
  {
    id: 95,
    label: 'Haiti',
    value: 'Haiti',
  },
  {
    id: 96,
    label: 'Heard Island and McDonald Islands',
    value: 'Heard Island and McDonald Islands',
  },
  {
    id: 97,
    label: 'Honduras',
    value: 'Honduras',
  },
  {
    id: 98,
    label: 'Hong Kong S.A.R.',
    value: 'Hong Kong S.A.R.',
  },
  {
    id: 99,
    label: 'Hungary',
    value: 'Hungary',
  },
  {
    id: 100,
    label: 'Iceland',
    value: 'Iceland',
  },
  {
    id: 101,
    label: 'India',
    value: 'India',
  },
  {
    id: 102,
    label: 'Indonesia',
    value: 'Indonesia',
  },
  {
    id: 103,
    label: 'Iran',
    value: 'Iran',
  },
  {
    id: 104,
    label: 'Iraq',
    value: 'Iraq',
  },
  {
    id: 105,
    label: 'Ireland',
    value: 'Ireland',
  },
  {
    id: 106,
    label: 'Israel',
    value: 'Israel',
  },
  {
    id: 107,
    label: 'Italy',
    value: 'Italy',
  },
  {
    id: 108,
    label: 'Jamaica',
    value: 'Jamaica',
  },
  {
    id: 109,
    label: 'Japan',
    value: 'Japan',
  },
  {
    id: 110,
    label: 'Jersey',
    value: 'Jersey',
  },
  {
    id: 111,
    label: 'Jordan',
    value: 'Jordan',
  },
  {
    id: 112,
    label: 'Kazakhstan',
    value: 'Kazakhstan',
  },
  {
    id: 113,
    label: 'Kenya',
    value: 'Kenya',
  },
  {
    id: 114,
    label: 'Kiribati',
    value: 'Kiribati',
  },
  {
    id: 115,
    label: 'North Korea',
    value: 'North Korea',
  },
  {
    id: 116,
    label: 'South Korea',
    value: 'South Korea',
  },
  {
    id: 117,
    label: 'Kuwait',
    value: 'Kuwait',
  },
  {
    id: 118,
    label: 'Kyrgyzstan',
    value: 'Kyrgyzstan',
  },
  {
    id: 119,
    label: 'Laos',
    value: 'Laos',
  },
  {
    id: 120,
    label: 'Latvia',
    value: 'Latvia',
  },
  {
    id: 121,
    label: 'Lebanon',
    value: 'Lebanon',
  },
  {
    id: 122,
    label: 'Lesotho',
    value: 'Lesotho',
  },
  {
    id: 123,
    label: 'Liberia',
    value: 'Liberia',
  },
  {
    id: 124,
    label: 'Libya',
    value: 'Libya',
  },
  {
    id: 125,
    label: 'Liechtenstein',
    value: 'Liechtenstein',
  },
  {
    id: 126,
    label: 'Lithuania',
    value: 'Lithuania',
  },
  {
    id: 127,
    label: 'Luxembourg',
    value: 'Luxembourg',
  },
  {
    id: 128,
    label: 'Macau S.A.R.',
    value: 'Macau S.A.R.',
  },
  {
    id: 129,
    label: 'Macedonia',
    value: 'Macedonia',
  },
  {
    id: 130,
    label: 'Madagascar',
    value: 'Madagascar',
  },
  {
    id: 131,
    label: 'Malawi',
    value: 'Malawi',
  },
  {
    id: 132,
    label: 'Malaysia',
    value: 'Malaysia',
  },
  {
    id: 133,
    label: 'Maldives',
    value: 'Maldives',
  },
  {
    id: 134,
    label: 'Mali',
    value: 'Mali',
  },
  {
    id: 135,
    label: 'Malta',
    value: 'Malta',
  },
  {
    id: 136,
    label: 'Man (Isle of)',
    value: 'Man (Isle of)',
  },
  {
    id: 137,
    label: 'Marshall Islands',
    value: 'Marshall Islands',
  },
  {
    id: 138,
    label: 'Martinique',
    value: 'Martinique',
  },
  {
    id: 139,
    label: 'Mauritania',
    value: 'Mauritania',
  },
  {
    id: 140,
    label: 'Mauritius',
    value: 'Mauritius',
  },
  {
    id: 141,
    label: 'Mayotte',
    value: 'Mayotte',
  },
  {
    id: 142,
    label: 'Mexico',
    value: 'Mexico',
  },
  {
    id: 143,
    label: 'Micronesia',
    value: 'Micronesia',
  },
  {
    id: 144,
    label: 'Moldova',
    value: 'Moldova',
  },
  {
    id: 145,
    label: 'Monaco',
    value: 'Monaco',
  },
  {
    id: 146,
    label: 'Mongolia',
    value: 'Mongolia',
  },
  {
    id: 147,
    label: 'Montenegro',
    value: 'Montenegro',
  },
  {
    id: 148,
    label: 'Montserrat',
    value: 'Montserrat',
  },
  {
    id: 149,
    label: 'Morocco',
    value: 'Morocco',
  },
  {
    id: 150,
    label: 'Mozambique',
    value: 'Mozambique',
  },
  {
    id: 151,
    label: 'Myanmar',
    value: 'Myanmar',
  },
  {
    id: 152,
    label: 'Namibia',
    value: 'Namibia',
  },
  {
    id: 153,
    label: 'Nauru',
    value: 'Nauru',
  },
  {
    id: 154,
    label: 'Nepal',
    value: 'Nepal',
  },
  {
    id: 155,
    label: 'Bonaire, Sint Eustatius and Saba',
    value: 'Bonaire, Sint Eustatius and Saba',
  },
  {
    id: 156,
    label: 'Netherlands',
    value: 'Netherlands',
  },
  {
    id: 157,
    label: 'New Caledonia',
    value: 'New Caledonia',
  },
  {
    id: 158,
    label: 'New Zealand',
    value: 'New Zealand',
  },
  {
    id: 159,
    label: 'Nicaragua',
    value: 'Nicaragua',
  },
  {
    id: 160,
    label: 'Niger',
    value: 'Niger',
  },
  {
    id: 161,
    label: 'Nigeria',
    value: 'Nigeria',
  },
  {
    id: 162,
    label: 'Niue',
    value: 'Niue',
  },
  {
    id: 163,
    label: 'Norfolk Island',
    value: 'Norfolk Island',
  },
  {
    id: 164,
    label: 'Northern Mariana Islands',
    value: 'Northern Mariana Islands',
  },
  {
    id: 165,
    label: 'Norway',
    value: 'Norway',
  },
  {
    id: 166,
    label: 'Oman',
    value: 'Oman',
  },
  {
    id: 167,
    label: 'Pakistan',
    value: 'Pakistan',
  },
  {
    id: 168,
    label: 'Palau',
    value: 'Palau',
  },
  {
    id: 169,
    label: 'Palestinian Territory Occupied',
    value: 'Palestinian Territory Occupied',
  },
  {
    id: 170,
    label: 'Panama',
    value: 'Panama',
  },
  {
    id: 171,
    label: 'Papua new Guinea',
    value: 'Papua new Guinea',
  },
  {
    id: 172,
    label: 'Paraguay',
    value: 'Paraguay',
  },
  {
    id: 173,
    label: 'Peru',
    value: 'Peru',
  },
  {
    id: 174,
    label: 'Philippines',
    value: 'Philippines',
  },
  {
    id: 175,
    label: 'Pitcairn Island',
    value: 'Pitcairn Island',
  },
  {
    id: 176,
    label: 'Poland',
    value: 'Poland',
  },
  {
    id: 177,
    label: 'Portugal',
    value: 'Portugal',
  },
  {
    id: 178,
    label: 'Puerto Rico',
    value: 'Puerto Rico',
  },
  {
    id: 179,
    label: 'Qatar',
    value: 'Qatar',
  },
  {
    id: 180,
    label: 'Reunion',
    value: 'Reunion',
  },
  {
    id: 181,
    label: 'Romania',
    value: 'Romania',
  },
  {
    id: 182,
    label: 'Russia',
    value: 'Russia',
  },
  {
    id: 183,
    label: 'Rwanda',
    value: 'Rwanda',
  },
  {
    id: 184,
    label: 'Saint Helena',
    value: 'Saint Helena',
  },
  {
    id: 185,
    label: 'Saint Kitts And Nevis',
    value: 'Saint Kitts And Nevis',
  },
  {
    id: 186,
    label: 'Saint Lucia',
    value: 'Saint Lucia',
  },
  {
    id: 187,
    label: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon',
  },
  {
    id: 188,
    label: 'Saint Vincent And The Grenadines',
    value: 'Saint Vincent And The Grenadines',
  },
  {
    id: 189,
    label: 'Saint-Barthelemy',
    value: 'Saint-Barthelemy',
  },
  {
    id: 190,
    label: 'Saint-Martin (French part)',
    value: 'Saint-Martin (French part)',
  },
  {
    id: 191,
    label: 'Samoa',
    value: 'Samoa',
  },
  {
    id: 192,
    label: 'San Marino',
    value: 'San Marino',
  },
  {
    id: 193,
    label: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
  },
  {
    id: 194,
    label: 'Saudi Arabia',
    value: 'Saudi Arabia',
  },
  {
    id: 195,
    label: 'Senegal',
    value: 'Senegal',
  },
  {
    id: 196,
    label: 'Serbia',
    value: 'Serbia',
  },
  {
    id: 197,
    label: 'Seychelles',
    value: 'Seychelles',
  },
  {
    id: 198,
    label: 'Sierra Leone',
    value: 'Sierra Leone',
  },
  {
    id: 199,
    label: 'Singapore',
    value: 'Singapore',
  },
  {
    id: 200,
    label: 'Slovakia',
    value: 'Slovakia',
  },
  {
    id: 201,
    label: 'Slovenia',
    value: 'Slovenia',
  },
  {
    id: 202,
    label: 'Solomon Islands',
    value: 'Solomon Islands',
  },
  {
    id: 203,
    label: 'Somalia',
    value: 'Somalia',
  },
  {
    id: 204,
    label: 'South Africa',
    value: 'South Africa',
  },
  {
    id: 205,
    label: 'South Georgia',
    value: 'South Georgia',
  },
  {
    id: 206,
    label: 'South Sudan',
    value: 'South Sudan',
  },
  {
    id: 207,
    label: 'Spain',
    value: 'Spain',
  },
  {
    id: 208,
    label: 'Sri Lanka',
    value: 'Sri Lanka',
  },
  {
    id: 209,
    label: 'Sudan',
    value: 'Sudan',
  },
  {
    id: 210,
    label: 'Suriname',
    value: 'Suriname',
  },
  {
    id: 211,
    label: 'Svalbard And Jan Mayen Islands',
    value: 'Svalbard And Jan Mayen Islands',
  },
  {
    id: 212,
    label: 'Swaziland',
    value: 'Swaziland',
  },
  {
    id: 213,
    label: 'Sweden',
    value: 'Sweden',
  },
  {
    id: 214,
    label: 'Switzerland',
    value: 'Switzerland',
  },
  {
    id: 215,
    label: 'Syria',
    value: 'Syria',
  },
  {
    id: 216,
    label: 'Taiwan',
    value: 'Taiwan',
  },
  {
    id: 217,
    label: 'Tajikistan',
    value: 'Tajikistan',
  },
  {
    id: 218,
    label: 'Tanzania',
    value: 'Tanzania',
  },
  {
    id: 219,
    label: 'Thailand',
    value: 'Thailand',
  },
  {
    id: 220,
    label: 'Togo',
    value: 'Togo',
  },
  {
    id: 221,
    label: 'Tokelau',
    value: 'Tokelau',
  },
  {
    id: 222,
    label: 'Tonga',
    value: 'Tonga',
  },
  {
    id: 223,
    label: 'Trinidad And Tobago',
    value: 'Trinidad And Tobago',
  },
  {
    id: 224,
    label: 'Tunisia',
    value: 'Tunisia',
  },
  {
    id: 225,
    label: 'Turkey',
    value: 'Turkey',
  },
  {
    id: 226,
    label: 'Turkmenistan',
    value: 'Turkmenistan',
  },
  {
    id: 227,
    label: 'Turks And Caicos Islands',
    value: 'Turks And Caicos Islands',
  },
  {
    id: 228,
    label: 'Tuvalu',
    value: 'Tuvalu',
  },
  {
    id: 229,
    label: 'Uganda',
    value: 'Uganda',
  },
  {
    id: 230,
    label: 'Ukraine',
    value: 'Ukraine',
  },
  {
    id: 231,
    label: 'United Arab Emirates',
    value: 'United Arab Emirates',
  },
  {
    id: 232,
    label: 'United Kingdom',
    value: 'United Kingdom',
  },
  {
    id: 233,
    label: 'United States',
    value: 'United States',
  },
  {
    id: 234,
    label: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  },
  {
    id: 235,
    label: 'Uruguay',
    value: 'Uruguay',
  },
  {
    id: 236,
    label: 'Uzbekistan',
    value: 'Uzbekistan',
  },
  {
    id: 237,
    label: 'Vanuatu',
    value: 'Vanuatu',
  },
  {
    id: 238,
    label: 'Vatican City State (Holy See)',
    value: 'Vatican City State (Holy See)',
  },
  {
    id: 239,
    label: 'Venezuela',
    value: 'Venezuela',
  },
  {
    id: 240,
    label: 'Vietnam',
    value: 'Vietnam',
  },
  {
    id: 241,
    label: 'Virgin Islands (British)',
    value: 'Virgin Islands (British)',
  },
  {
    id: 242,
    label: 'Virgin Islands (US)',
    value: 'Virgin Islands (US)',
  },
  {
    id: 243,
    label: 'Wallis And Futuna Islands',
    value: 'Wallis And Futuna Islands',
  },
  {
    id: 244,
    label: 'Western Sahara',
    value: 'Western Sahara',
  },
  {
    id: 245,
    label: 'Yemen',
    value: 'Yemen',
  },
  {
    id: 246,
    label: 'Zambia',
    value: 'Zambia',
  },
  {
    id: 247,
    label: 'Zimbabwe',
    value: 'Zimbabwe',
  },
  {
    id: 248,
    label: 'Kosovo',
    value: 'Kosovo',
  },
  {
    id: 249,
    label: 'Curaçao',
    value: 'Curaçao',
  },
  {
    id: 250,
    label: 'Sint Maarten (Dutch part)',
    value: 'Sint Maarten (Dutch part)',
  },
];

export const documentType = [
  {
    label: 'Aadhar Card',
    value: 'Aadhaar',
  },
  {
    label: 'Driving License',
    value: 'Driving License',
  },
  {
    label: 'Other',
    value: 'Passport',
  },
];

export const documentType2 = [
  {
    label: 'Driving License',
    value: 'Driving License',
  },
  {
    label: 'Passport',
    value: 'Passport',
  },
];

export const percentageData = [
  {
    value: 25,
  },
  {
    value: 50,
  },
  {
    value: 75,
  },
  {
    value: 100,
  },
];

export const routes = [
  {key: 'first', title: 'Mobile'},
  {key: 'second', title: 'Email'},
];

export const countryCodes = [
  {label: '+93', value: '93'},
  {label: '+355', value: '355'},
  {label: '+213', value: '213'},
  {label: '+376', value: '376'},
  {label: '+244', value: '244'},
  {label: '+672', value: '672'},
  {label: '+54', value: '54'},
  {label: '+374', value: '374'},
  {label: '+297', value: '297'},
  {label: '+61', value: '61'},
  {label: '+43', value: '43'},
  {label: '+994', value: '994'},
  {label: '+973', value: '973'},
  {label: '+880', value: '880'},
  {label: '+375', value: '375'},
  {label: '+32', value: '32'},
  {label: '+501', value: '501'},
  {label: '+229', value: '229'},
  {label: '+975', value: '975'},
  {label: '+591', value: '591'},
  {label: '+387', value: '387'},
  {label: '+267', value: '267'},
  {label: '+55', value: '55'},
  {label: '+246', value: '246'},
  {label: '+673', value: '673'},
  {label: '+359', value: '359'},
  {label: '+226', value: '226'},
  {label: '+257', value: '257'},
  {label: '+855', value: '855'},
  {label: '+237', value: '237'},
  {label: '+1', value: '1'},
  {label: '+238', value: '238'},
  {label: '+236', value: '236'},
  {label: '+235', value: '235'},
  {label: '+56', value: '56'},
  {label: '+86', value: '86'},
  {label: '+61', value: '61'},
  {label: '+61', value: '61'},
  {label: '+57', value: '57'},
  {label: '+269', value: '269'},
  {label: '+682', value: '682'},
  {label: '+506', value: '506'},
  {label: '+385', value: '385'},
  {label: '+53', value: '53'},
  {label: '+599', value: '599'},
  {label: '+357', value: '357'},
  {label: '+420', value: '420'},
  {label: '+243', value: '243'},
  {label: '+45', value: '45'},
  {label: '+253', value: '253'},
  {label: '+670', value: '670'},
  {label: '+593', value: '593'},
  {label: '+20', value: '20'},
  {label: '+503', value: '503'},
  {label: '+240', value: '240'},
  {label: '+291', value: '291'},
  {label: '+372', value: '372'},
  {label: '+251', value: '251'},
  {label: '+500', value: '500'},
  {label: '+298', value: '298'},
  {label: '+679', value: '679'},
  {label: '+358', value: '358'},
  {label: '+33', value: '33'},
  {label: '+689', value: '689'},
  {label: '+241', value: '241'},
  {label: '+220', value: '220'},
  {label: '+995', value: '995'},
  {label: '+49', value: '49'},
  {label: '+233', value: '233'},
  {label: '+350', value: '350'},
  {label: '+30', value: '30'},
  {label: '+299', value: '299'},
  {label: '+502', value: '502'},
  {label: '+224', value: '224'},
  {label: '+245', value: '245'},
  {label: '+592', value: '592'},
  {label: '+509', value: '509'},
  {label: '+504', value: '504'},
  {label: '+852', value: '852'},
  {label: '+36', value: '36'},
  {label: '+354', value: '354'},
  {label: '+91', value: '91'},
  {label: '+62', value: '62'},
  {label: '+98', value: '98'},
  {label: '+964', value: '964'},
  {label: '+353', value: '353'},
  {label: '+972', value: '972'},
  {label: '+39', value: '39'},
  {label: '+225', value: '225'},
  {label: '+81', value: '81'},
  {label: '+962', value: '962'},
  {label: '+7', value: '7'},
  {label: '+254', value: '254'},
  {label: '+686', value: '686'},
  {label: '+383', value: '383'},
  {label: '+965', value: '965'},
  {label: '+996', value: '996'},
  {label: '+856', value: '856'},
  {label: '+371', value: '371'},
  {label: '+961', value: '961'},
  {label: '+266', value: '266'},
  {label: '+231', value: '231'},
  {label: '+218', value: '218'},
  {label: '+423', value: '423'},
  {label: '+370', value: '370'},
  {label: '+352', value: '352'},
  {label: '+853', value: '853'},
  {label: '+389', value: '389'},
  {label: '+261', value: '261'},
  {label: '+265', value: '265'},
  {label: '+60', value: '60'},
  {label: '+960', value: '960'},
  {label: '+223', value: '223'},
  {label: '+356', value: '356'},
  {label: '+692', value: '692'},
  {label: '+222', value: '222'},
  {label: '+230', value: '230'},
  {label: '+262', value: '262'},
  {label: '+52', value: '52'},
  {label: '+691', value: '691'},
  {label: '+373', value: '373'},
  {label: '+377', value: '377'},
  {label: '+976', value: '976'},
  {label: '+382', value: '382'},
  {label: '+212', value: '212'},
  {label: '+258', value: '258'},
  {label: '+95', value: '95'},
  {label: '+264', value: '264'},
  {label: '+674', value: '674'},
  {label: '+977', value: '977'},
  {label: '+31', value: '31'},
  {label: '+599', value: '599'},
  {label: '+687', value: '687'},
  {label: '+64', value: '64'},
  {label: '+505', value: '505'},
  {label: '+227', value: '227'},
  {label: '+234', value: '234'},
  {label: '+683', value: '683'},
  {label: '+850', value: '850'},
  {label: '+47', value: '47'},
  {label: '+968', value: '968'},
  {label: '+92', value: '92'},
  {label: '+680', value: '680'},
  {label: '+970', value: '970'},
  {label: '+507', value: '507'},
  {label: '+675', value: '675'},
  {label: '+595', value: '595'},
  {label: '+51', value: '51'},
  {label: '+63', value: '63'},
  {label: '+64', value: '64'},
  {label: '+48', value: '48'},
  {label: '+351', value: '351'},
  {label: '+974', value: '974'},
  {label: '+242', value: '242'},
  {label: '+262', value: '262'},
  {label: '+40', value: '40'},
  {label: '+7', value: '7'},
  {label: '+250', value: '250'},
  {label: '+590', value: '590'},
  {label: '+290', value: '290'},
  {label: '+590', value: '590'},
  {label: '+508', value: '508'},
  {label: '+685', value: '685'},
  {label: '+378', value: '378'},
  {label: '+239', value: '239'},
  {label: '+966', value: '966'},
  {label: '+221', value: '221'},
  {label: '+381', value: '381'},
  {label: '+248', value: '248'},
  {label: '+232', value: '232'},
  {label: '+65', value: '65'},
  {label: '+421', value: '421'},
  {label: '+386', value: '386'},
  {label: '+677', value: '677'},
  {label: '+252', value: '252'},
  {label: '+27', value: '27'},
  {label: '+82', value: '82'},
  {label: '+211', value: '211'},
  {label: '+34', value: '34'},
  {label: '+94', value: '94'},
  {label: '+249', value: '249'},
  {label: '+597', value: '597'},
  {label: '+47', value: '47'},
  {label: '+268', value: '268'},
  {label: '+46', value: '46'},
  {label: '+41', value: '41'},
  {label: '+963', value: '963'},
  {label: '+886', value: '886'},
  {label: '+992', value: '992'},
  {label: '+255', value: '255'},
  {label: '+66', value: '66'},
  {label: '+228', value: '228'},
  {label: '+690', value: '690'},
  {label: '+676', value: '676'},
  {label: '+216', value: '216'},
  {label: '+90', value: '90'},
  {label: '+993', value: '993'},
  {label: '+688', value: '688'},
  {label: '+256', value: '256'},
  {label: '+380', value: '380'},
  {label: '+971', value: '971'},
  {label: '+44', value: '44'},
  {label: '+1', value: '1'},
  {label: '+598', value: '598'},
  {label: '+998', value: '998'},
  {label: '+678', value: '678'},
  {label: '+379', value: '379'},
  {label: '+58', value: '58'},
  {label: '+84', value: '84'},
  {label: '+681', value: '681'},
  {label: '+212', value: '212'},
  {label: '+967', value: '967'},
  {label: '+260', value: '260'},
  {label: '+263', value: '263'},
];


export const slideData = [
  {
    id: 0,
    name: 'Spot',
  },
  // {
  //   id: 1,
  //   name: 'Launchpad',
  // },
  // {
  //   id: 2,
  //   name: 'Staking',
  // },
];